name: Downgraded Release

on:
  push:
    tags:
      - '*'

jobs:
  downgrade_release:
    runs-on: ubuntu-latest
    steps:
      -
        uses: "actions/checkout@v4"

      -
        uses: "shivammathur/setup-php@2.28.0"
        with:
          php-version: 8.1
          coverage: none

      -   uses: "ramsey/composer-install@v2"

      # downgrade /src to PHP 7.4
      -   run: composer bin all install
      -   run: vendor/bin/rector process src --config build/rector-downgrade-php-74.php --ansi
      -   run: vendor/bin/ecs check src --fix --ansi

      # copy PHP 7.4 composer
      -   run: cp build/composer-php-74.json composer.json

      # clear the dev files
      -   run: rm -rf build .github tests tools .docheader ecs.php phpstan.neon phpstan-baseline.neon phpunit.xml psalm.xml psalm-baseline

      # setup git user
      -
        run: |
          git config user.email "action@github.com"
          git config user.name "GitHub Action"

      # publish to the same repository with a new tag
      -
        name: "Tag Downgraded Code"
        run: |
          git commit -a -m "release PHP 7.4 downgraded ${GITHUB_REF#refs/tags/}"
          git tag "${GITHUB_REF#refs/tags/}.74"
          git push origin "${GITHUB_REF#refs/tags/}.74"
